/* Control Room Ledger: compact industrial density, semantic signal colors, visible traceability. */
import { useEffect, useMemo, useRef, useState } from "react";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, Check, ChevronRight, Circle,
  ClipboardCheck, Clock3, Database, FileText, Gauge, LockKeyhole, Menu, Network, Radar, Settings2,
  RefreshCw, Search, ShieldCheck, SlidersHorizontal, UserRound, X, Zap
} from "lucide-react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { NOTIFICATION_POLL_INTERVAL_MS, refreshUnreadNotifications } from "@/lib/notificationTransport";
import EdgeAdapterHealthCard from "@/components/EdgeAdapterHealthCard";
import { identityCopy } from "@/lib/identityCopy";
import { getUnreadNotifications } from "@/lib/notificationState";

type OperationRow = { id: string; time: string; source: string; variable: string; tag: string; current: string; requested: string; unit: string; uc: string; status: string; sil: string; delta: string; equipment: string };

const checks = ["EQUIPMENT_CHECK", "SIGNATURE_CHECK", "UNIT_CHECK", "DUPLICATE_CHECK", "TTL_CHECK", "RANGE_CHECK", "SIL_CHECK", "ROC_CHECK", "INTERLOCK_CHECK"];
const nav = [
  { label: "Operations", icon: Activity, active: true, href: "/operations" }, { label: "Requests", icon: FileText, href: "/requests" },
  { label: "Approvals", icon: ClipboardCheck, href: "/approvals" }, { label: "Validation", icon: ShieldCheck, href: "/validation" },
  { label: "Audit trail", icon: Database, href: "/audit" }, { label: "System health", icon: Radar, href: "/system-health" }, { label: "Analytics", icon: Gauge, href: "/analytics" }, { label: "NE178 compliance", icon: ShieldCheck, href: "/compliance" }, { label: "Configuration", icon: Settings2, href: "/configuration" },
];

function Status({ value }: { value: string }) {
  const config: Record<string, { cls: string; label: string }> = {
    ACCEPTED: { cls: "status-green", label: "ACCEPTED" }, REJECTED: { cls: "status-red", label: "REJECTED" },
    PENDING_OPERATOR: { cls: "status-amber", label: "PENDING OPERATOR" }, DUPLICATED: { cls: "status-slate", label: "DUPLICATED" }, EXPIRED: { cls: "status-slate", label: "EXPIRED" },
  };
  const item = config[value] || config.ACCEPTED;
  return <span className={`status ${item.cls}`}><span className="status-dot" />{item.label}</span>;
}

export default function Home() {
  const [, navigate] = useLocation();
  const auth = useAuth();
  const notificationsQuery = trpc.notifications.list.useQuery({ unreadOnly: false }, { enabled: Boolean(auth.user), refetchInterval: NOTIFICATION_POLL_INTERVAL_MS, retry: false });
  const refreshNotifications = () => { void notificationsQuery.refetch(); };
  const unreadNotifications = getUnreadNotifications(notificationsQuery.data ?? []);
  const markNotificationRead = trpc.notifications.markRead.useMutation({ onSuccess: result => { refreshNotifications(); if (result.updated) toast.success("Alert acknowledged and cleared from the unread queue."); else toast.error("Alert is no longer available to acknowledge."); }, onError: error => toast.error(error.message) });
  const markAllNotificationsRead = trpc.notifications.markAllRead.useMutation({ onSuccess: result => { refreshNotifications(); toast.success(result.updated ? `${result.updated} alert${result.updated === 1 ? "" : "s"} acknowledged.` : "No persisted alerts required acknowledgement."); }, onError: error => toast.error(error.message) });
  const requestQuery = trpc.requests.list.useQuery(undefined, { enabled: Boolean(auth.user), retry: false });
  const catalogQuery = trpc.requests.catalog.useQuery(undefined, { enabled: Boolean(auth.user), retry: false });
  const governanceSummaryQuery = trpc.dashboard.operationsSummary.useQuery(undefined, { enabled: Boolean(auth.user), refetchInterval: NOTIFICATION_POLL_INTERVAL_MS, retry: false });
  useEffect(() => { if (!auth.user) return; if (typeof EventSource === "undefined") { void refreshUnreadNotifications(false, notificationsQuery.refetch); return; } const stream = new EventSource("/api/notifications/stream"); const handle = (event: MessageEvent<string>) => { refreshNotifications(); try { const next = JSON.parse(event.data) as { title?: string; message?: string }; if (next.title) toast(`${next.title}: ${next.message || "Review required."}`); } catch { /* polling remains authoritative */ } }; stream.addEventListener("notification", handle); return () => { stream.removeEventListener("notification", handle); stream.close(); }; }, [auth.user?.id, notificationsQuery.refetch]);
  const previewAlerts = [{ id: -1, severity: "WARNING", title: "Approval required / preview", message: "Simulator alert preview — persisted alerts appear here when canonical rows exist.", createdAt: new Date() }];
  const visibleNotifications = unreadNotifications.length ? unreadNotifications : notificationsQuery.data?.length ? [] : previewAlerts;
  const unreadCount = visibleNotifications.length;
  const [selected, setSelected] = useState<OperationRow | null>(null);
  const [drawer, setDrawer] = useState(false);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const requestSearchRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState("");
  const equipmentById = useMemo(() => new Map((catalogQuery.data?.equipment || []).map(item => [item.id, item])), [catalogQuery.data]);
  const variableById = useMemo(() => new Map((catalogQuery.data?.variables || []).map(item => [item.id, item])), [catalogQuery.data]);
  const canonicalRequests = useMemo(() => (requestQuery.data || []).map(row => { const equipment = equipmentById.get(row.equipmentId); const variable = variableById.get(row.variableId); const deltaValue = Number(row.requestedSp) - Number(row.currentPv); return { id: row.requestId, time: new Date(row.createdAt).toISOString().slice(11, 19), source: row.sourceUc, variable: variable?.name || `Variable ${row.variableId}`, tag: variable?.tag || String(row.variableId), current: String(row.currentPv), requested: String(row.requestedSp), unit: variable?.unit || "—", uc: row.sourceUc, status: row.status, sil: variable?.silClass || "—", delta: Number.isFinite(deltaValue) ? `${deltaValue >= 0 ? "+" : ""}${deltaValue}` : "—", equipment: equipment?.tag || String(row.equipmentId) }; }), [equipmentById, variableById, requestQuery.data]);
  const dataError = requestQuery.error || catalogQuery.error;
  const operationalRequests: OperationRow[] = dataError ? [] : canonicalRequests;
  const operationalSource = dataError ? "DATA UNAVAILABLE" : canonicalRequests.length ? "CANONICAL DB / READ-ONLY" : "NO CANONICAL REQUESTS";
  const telemetry = useMemo(() => {
    const valueFor = (term: string) => canonicalRequests.find(row => row.variable.toLowerCase().includes(term))?.current ?? "—";
    return { temperature: valueFor("temperature"), sulfate: valueFor("sulfate"), p205: valueFor("p2o5"), solids: valueFor("solids") };
  }, [canonicalRequests]);
  const operationalStats = useMemo(() => {
    const total = operationalRequests.length;
    const count = (status: string) => operationalRequests.filter(row => row.status === status).length;
    const accepted = count("ACCEPTED");
    return { total, accepted, rejected: count("REJECTED"), pending: count("PENDING_OPERATOR"), duplicated: count("DUPLICATED"), expired: count("EXPIRED"), acceptanceRate: total ? ((accepted / total) * 100).toFixed(1) : "0.0" };
  }, [operationalRequests]);
  const filtered = useMemo(() => operationalRequests.filter(r => Object.values(r).join(" ").toLowerCase().includes(query.toLowerCase())), [query, operationalRequests]);
  const selectRequest = (r: OperationRow) => { setSelected(r); setDrawer(true); };
  useEffect(() => { if (!selected || !canonicalRequests.some(row => row.id === selected.id)) setSelected(canonicalRequests[0] ?? null); }, [canonicalRequests, selected]);

  return (
    <div className="app-shell">
      <aside className={`sidebar ${mobileNavOpen ? "mobile-open" : ""}`}>
        <div className="brand-block"><div className="brand-lockup"><img src="/manus-storage/jesa-wordmark_e357ca66.png" className="jesa-logo" alt="JESA" /></div><div className="brand-rule" /><div><div className="eyebrow">DIGITAL ENGINEERING</div><div className="brand-sub">VoR GATEWAY / PAP</div></div></div>
        <div className="plant-selector"><div className="eyebrow">ACTIVE SYSTEM</div><div className="plant-name">Attack Reactor <ChevronRight size={14} /></div><div className="plant-meta"><span className="amber-dot" />EDGE ADAPTER DISCONNECTED · READ-ONLY</div></div>
        <nav className="nav-list">{nav.filter(item => item.href !== "/configuration" || auth.user?.role === "admin").map(item => <Link href={item.href} key={item.label} onClick={() => setMobileNavOpen(false)} className={`nav-item ${item.active ? "active" : ""}`}><item.icon size={16} /><span>{item.label}</span></Link>)}</nav>
        <div className="sidebar-foot"><div className="zone-card"><div className="eyebrow">SECURITY ZONES</div><div className="zone-row"><span className="zone-dot blue" />MODULE 3 · psM+O <Check size={13} /></div><div className="zone-row"><span className="zone-dot amber" />MODULE 2 · DMZ <Check size={13} /></div><div className="zone-row"><span className="zone-dot green" />MODULE 1 · CPC <Check size={13} /></div></div><div className="user-row"><div className="avatar">OP</div><div><strong>{identityCopy.operatorDisplay}</strong><small>{identityCopy.operatorLabel}</small></div><button className="user-logout" onClick={() => auth.logout().then(() => navigate("/login"))} aria-label="Log out"><LockKeyhole size={14} /></button></div></div>
      </aside>

      <main className="main-content">
        <header className="topbar"><div className="breadcrumb"><span>JESA / DIGITAL ENGINEERING</span><ChevronRight size={13} /><strong>OPERATIONS</strong></div><div className="top-actions"><div className="system-pulse"><span className="live-dot" /> GATEWAY ONLINE · EDGE DISCONNECTED</div><button className="icon-btn notification-trigger" aria-label="Notifications" onClick={() => toast(unreadCount ? `${unreadCount} unread operating alert${unreadCount === 1 ? "" : "s"}.` : "No unread operating alerts.")}><Bell size={17} />{Boolean(unreadCount) && <b>{unreadCount}</b>}<i /></button><button className="icon-btn" onClick={() => toast(identityCopy.sessionToast)}><LockKeyhole size={16} /></button><button className="menu-btn" aria-label="Toggle navigation" aria-expanded={mobileNavOpen} onClick={() => setMobileNavOpen(open => !open)}><Menu size={18} /></button></div></header>
        {Boolean(visibleNotifications.length) && <div className="notification-tray"><div className="notification-tray-head"><span><span className="live-dot" /> {unreadCount} UNREAD OPERATING ALERT{unreadCount === 1 ? "" : "S"}</span><div><small>{notificationsQuery.data?.length ? "REAL-TIME CHANNEL" : "SIMULATOR PREVIEW / NO PERSISTED ALERTS"}</small>{Boolean(notificationsQuery.data?.length) && <button className="notification-clear-btn" type="button" onClick={() => markAllNotificationsRead.mutate()} disabled={markAllNotificationsRead.isPending}>{markAllNotificationsRead.isPending ? "ACKNOWLEDGING…" : "ACKNOWLEDGE ALL"}</button>}</div></div>{visibleNotifications.slice(0, 3).map(notification => <button key={notification.id} className={`notification-item notification-${notification.severity.toLowerCase()}`} onClick={() => notification.id === -1 ? toast("Preview alert only. Run the seeded workflow simulation or receive a canonical event to create a persisted alert.") : markNotificationRead.mutate({ notificationId: notification.id })} disabled={notification.id !== -1 && markNotificationRead.isPending}><strong>{notification.title}</strong><span>{notification.message}</span><small>{new Date(notification.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })} · {notification.id === -1 ? "PREVIEW ONLY" : "CLICK TO ACKNOWLEDGE"}</small></button>)}</div>}
        <div className="content-wrap">
          <section className="page-heading"><div><div className="eyebrow cobalt">PAP ATTACK REACTOR / CONTROL SYSTEM</div><h1>Verification of Request <span className="muted">/</span> Operations</h1><p>Secure request governance between APC and the DCS adapter. Every write is verified, mapped, and traceable.</p><div className="lineage-strip"><span className="lineage-label">REQUEST LINEAGE</span><strong>APC</strong><ChevronRight size={12} /><strong className="lineage-active">MODULE 3 / psM+O</strong><ChevronRight size={12} /><strong className="lineage-active">MODULE 2 / DMZ</strong><ChevronRight size={12} /><strong>MODULE 1 / CPC</strong><ChevronRight size={12} /><strong>DCS ADAPTER</strong></div></div><div className="heading-meta"><div className="meta-label">LAST SYNCHRONIZED</div><div className="mono">{canonicalRequests[0]?.time ?? "—"} UTC <RefreshCw size={13} /></div><div className="sim-label"><span className="live-dot" /> CANONICAL DB · READ-ONLY</div></div></section>

          {dataError && <section className="api-error-strip" role="alert"><div><div className="eyebrow red-label">OPERATIONS DATA UNAVAILABLE</div><strong>Protected backend data could not be loaded.</strong><p>{dataError.message || "The canonical request and engineering catalog queries did not complete."} No simulator rows are substituted while an API error is active.</p></div><button type="button" onClick={() => { void requestQuery.refetch(); void catalogQuery.refetch(); }} disabled={requestQuery.isFetching || catalogQuery.isFetching}>{requestQuery.isFetching || catalogQuery.isFetching ? "RETRYING…" : "RETRY DATA"}</button></section>}

          <section className="kpi-strip">
            <div className="kpi"><div className="kpi-label">REQUESTS / CURRENT QUERY <span className="trend"><Database size={12} /> {operationalSource}</span></div><strong>{operationalStats.total}</strong><small>records available to this session</small></div>
            <div className="kpi"><div className="kpi-label">ACCEPTANCE RATE <span className="trend"><ArrowUpRight size={13} /> DERIVED</span></div><strong>{operationalStats.acceptanceRate}<span className="unit">%</span></strong><small>{operationalStats.accepted} accepted / {operationalStats.total} total</small></div>
            <div className="kpi"><div className="kpi-label">PENDING APPROVAL <span className="trend warn">ACTION REQUIRED</span></div><strong className="amber-text">{String(operationalStats.pending).padStart(2, "0")}</strong><small>four-eyes review required</small></div>
            <div className="kpi"><div className="kpi-label">STATE DISTRIBUTION <span className="trend"><Clock3 size={12} /> LIVE QUERY</span></div><strong>{operationalStats.rejected + operationalStats.duplicated + operationalStats.expired}</strong><small>{operationalStats.rejected} rejected · {operationalStats.duplicated} duplicated · {operationalStats.expired} expired</small></div>
          </section>

          <section className="governance-summary-panel panel" aria-labelledby="governance-summary-title">
            <div className="panel-head"><div><h2 id="governance-summary-title">Governance attention</h2><span className="panel-caption">CERTIFICATE EXPIRY / FOUR-EYES QUEUE · PROTECTED SUMMARY</span></div><span className="signal-badge"><span className="live-dot" /> LIVE</span></div>
            {governanceSummaryQuery.isLoading ? <div className="governance-summary-state"><RefreshCw size={15} className="spin" /> READING PROTECTED ALERT SUMMARY…</div> : governanceSummaryQuery.error ? <div className="governance-summary-state error" role="alert"><div><strong>SUMMARY UNAVAILABLE</strong><span>{governanceSummaryQuery.error.message}</span></div><button type="button" onClick={() => void governanceSummaryQuery.refetch()}>RETRY</button></div> : <div className="governance-summary-grid"><div className="governance-summary-column"><div className="governance-summary-label"><Bell size={14} /> CERTIFICATE EXPIRY ALERTS <strong>{governanceSummaryQuery.data?.expiryAlertCount ?? 0}</strong></div>{governanceSummaryQuery.data?.expiryAlerts.length ? governanceSummaryQuery.data.expiryAlerts.slice(0, 3).map(alert => <div className={`governance-alert-row ${alert.severity === "CRITICAL" ? "critical" : "warning"}`} key={alert.id}><span className="status-dot" /><div><strong>{alert.title}</strong><span>{alert.message}</span><small>{alert.readAt ? "ACKNOWLEDGED" : "UNACKNOWLEDGED"} · {new Date(alert.createdAt).toLocaleString()}</small></div></div>) : <div className="governance-empty">No certificate-expiry notifications are persisted for this authenticated recipient.</div>}</div><div className="governance-summary-column"><div className="governance-summary-label"><ClipboardCheck size={14} /> PENDING FOUR-EYES APPROVALS <strong>{governanceSummaryQuery.data?.pendingApprovalCount ?? "—"}</strong></div>{governanceSummaryQuery.data?.approvalVisibility === "AUTHORIZED" ? governanceSummaryQuery.data.pendingApprovals.length ? governanceSummaryQuery.data.pendingApprovals.slice(0, 3).map(approval => <Link href={`/requests/${approval.requestId}`} className="governance-approval-row" key={approval.id}><div><strong>{approval.requestId}</strong><span>{approval.variableName} · {approval.equipmentName}</span><small>{approval.priority} · {new Date(approval.createdAt).toLocaleString()}</small></div><span className="mono cobalt-text">{approval.requestedSp} {approval.unit}</span><ChevronRight size={15} /></Link>) : <div className="governance-empty">No pending approval rows are available to this authorized reviewer.</div> : <div className="governance-empty restricted"><LockKeyhole size={14} /> Approval detail is role-restricted to supervisors, engineers, and administrators.</div>}</div></div>}
            {!governanceSummaryQuery.isLoading && !governanceSummaryQuery.error && <div className="governance-summary-foot"><span>Recipient-scoped notifications · approval details are never exposed outside the authorized role boundary.</span><div>{Boolean(governanceSummaryQuery.data?.expiryAlertCount) && <button type="button" onClick={() => setDrawer(true)}>OPEN ALERT DRAWER</button>}{governanceSummaryQuery.data?.approvalVisibility === "AUTHORIZED" && <button type="button" onClick={() => navigate("/approvals")}>OPEN APPROVAL QUEUE <ChevronRight size={13} /></button>}</div></div>}
          </section>

          <div className="section-label"><span className="live-line-marker" /><span>CANONICAL REQUEST MONITOR</span><span className="sim-stream-tag"><span className="live-dot" /> PROTECTED READ-ONLY QUERY</span><span className="section-line" /><button className="pause-btn" onClick={() => void requestQuery.refetch()} disabled={requestQuery.isFetching}>{requestQuery.isFetching ? "REFRESHING…" : "REFRESH DATA"}</button></div>
          <section className="workbench">
            <div className="requests-panel panel"><div className="panel-head"><div><h2>Recent requests</h2><span className="panel-caption">APC → DMZ → CPC / newest first</span></div><div className="panel-tools"><div className="search"><Search size={14} /><input ref={requestSearchRef} placeholder="Filter requests" value={query} onChange={e => setQuery(e.target.value)} /></div><button className="filter-btn" onClick={() => requestSearchRef.current?.focus()}><SlidersHorizontal size={14} /> Filter</button></div></div><div className="request-table sim-request-stream"><div className="table-head"><span className="stream-scanline" /><span>REQUEST / TIME</span><span>SOURCE</span><span>VARIABLE / TAG</span><span>Δ REQUEST</span><span>DECISION</span></div>{filtered.map(r => <button className={`request-row ${selected?.id === r.id ? "selected" : ""}`} key={r.id} onClick={() => selectRequest(r)}><div><strong className="mono">{r.id}</strong><small>{r.time} UTC</small></div><div className="mono source">{r.source}</div><div><strong>{r.variable}</strong><small className="mono">{r.tag} · {r.uc}</small></div><div className={`mono delta ${r.delta.startsWith("+") ? "positive" : ""}`}>{r.delta} {r.unit}</div><Status value={r.status} /></button>)}</div><div className="panel-foot"><span>Showing {filtered.length} of {operationalStats.total} records · {operationalSource}</span><button onClick={() => navigate("/requests")}>VIEW REQUEST ARCHIVE <ChevronRight size={13} /></button></div></div>

            <aside className="decision-panel panel decision-rail"><div className="panel-head"><span className="rail-label">DECISION RAIL</span><div><h2>Gateway posture</h2><span className="panel-caption">LOCAL BASELINE · READ-ONLY</span></div><span className="signal-badge"><span className="live-dot" /> ONLINE</span></div><div className="posture-visual"><div className="ring"><div><strong>09</strong><span>CHECKS</span></div></div><div><div className="posture-title">Verification engine</div><div className="posture-copy">All mandatory checks available. No active interlocks.</div></div></div><div className="metric-list telemetry-stream"><div><span>Reactor temperature</span><strong className="telemetry-value">{telemetry.temperature} <em>°C</em></strong></div><div><span>Free sulfate</span><strong className="telemetry-value">{telemetry.sulfate} <em>g/L</em></strong></div><div><span>P<sub>2</sub>O<sub>5</sub></span><strong className="telemetry-value">{telemetry.p205} <em>%</em></strong></div><div><span>Slurry solids</span><strong className="telemetry-value">{telemetry.solids} <em>%</em></strong></div></div><div className="posture-note"><AlertTriangle size={14} /><span>{operationalStats.pending ? `${operationalStats.pending} request${operationalStats.pending === 1 ? "" : "s"} require operator approval before propagation.` : "No pending operator approvals in the current canonical query."}</span></div><EdgeAdapterHealthCard compact /><button className="primary-btn" onClick={() => navigate("/approvals")}>OPEN APPROVAL QUEUE <ChevronRight size={15} /></button></aside>
          </section>

          <div className="lower-grid"><section className="panel pipeline-panel"><div className="panel-head"><div><h2><span className="live-line-marker inline" />NE178-aligned processing pipeline</h2><span className="panel-caption">{selected?.id ?? canonicalRequests[0]?.id ?? "NO CANONICAL REQUEST SELECTED"}</span></div><span className={`status ${selected?.status === "ACCEPTED" ? "status-green" : selected ? "status-amber" : "status-slate"}`}><span className="status-dot" /> {selected?.status ?? "NO DATA"}</span></div><div className="pipeline">{["AUTHENTICATE", "VERIFY", "MAP", "PROPAGATE", "ACCEPT", "VERIFY MAP"].map((s, i) => <div className="pipe-step" key={s}><div className="pipe-icon"><Check size={14} /></div><div><strong>0{i + 1}</strong><span>{s}</span></div>{i < 5 && <ChevronRight className="pipe-arrow" size={16} />}</div>)}</div></section><section className="panel audit-panel"><div className="panel-head"><div><h2>Audit activity</h2><span className="panel-caption">IMMUTABLE EVENT STREAM</span></div><button className="text-btn" onClick={() => navigate("/audit")}>OPEN LOG <ChevronRight size={13} /></button></div><div className="audit-list"><div><span className="audit-marker blue" /><p><strong>Canonical audit events are available in Audit trail</strong><small>{operationalStats.total ? `${operationalStats.total} request records in the current protected query.` : "No canonical request records are available."}</small></p></div></div></section></div>
          <footer><span>© 2026 JESA S.A. · CONFIDENTIAL — PROPRIETARY INFORMATION</span><span><span className="amber-dot" /> READ-ONLY EDGE BOUNDARY · NO PLANT WRITE PATH</span></footer>
        </div>
      </main>

      {drawer && selected && <div className="drawer-backdrop" onClick={() => setDrawer(false)}><aside className="detail-drawer" onClick={e => e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow cobalt">REQUEST DETAIL</div><h2>{selected.id}</h2><Status value={selected.status} /></div><button className="icon-btn" onClick={() => setDrawer(false)}><X size={18} /></button></div><div className="drawer-section"><div className="drawer-label">WHAT / WHERE</div><div className="detail-grid"><div><small>VARIABLE</small><strong>{selected.variable}</strong></div><div><small>TAG</small><strong className="mono">{selected.tag}</strong></div><div><small>EQUIPMENT</small><strong>{selected.equipment}</strong></div><div><small>PROCESS AREA</small><strong>UC1 / Attack & Digestion</strong></div></div></div><div className="drawer-section"><div className="drawer-label">CURRENT → REQUESTED</div><div className="compare"><div><small>CURRENT PV</small><strong>{selected.current} <em>{selected.unit}</em></strong></div><ArrowRightIcon /><div><small>REQUESTED SP</small><strong className="cobalt-text">{selected.requested} <em>{selected.unit}</em></strong></div></div><div className="delta-box"><span>DELTA / RATE OF CHANGE</span><strong>{selected.delta} {selected.unit} <span className="positive">WITHIN ROC</span></strong></div></div><div className="drawer-section"><div className="drawer-label">NINE-STEP VALIDATION SEQUENCE</div><div className="check-list">{checks.map((c, i) => <div key={c} className={`check-row ${i > 5 && selected.status === "REJECTED" ? "not-run" : ""}`}><span className={`check-icon ${i > 5 && selected.status === "REJECTED" ? "muted-check" : ""}`}>{i > 5 && selected.status === "REJECTED" ? <Circle size={9} /> : <Check size={12} />}</span><span>{c}</span><strong>{i > 5 && selected.status === "REJECTED" ? "NOT EXECUTED" : "PASS"}</strong></div>)}</div></div><div className="drawer-section trace-section"><div className="drawer-label">TRACEABILITY</div><div className="trace-row"><LockKeyhole size={14} /><span>Certificate subject</span><strong className="mono">PERSISTED IN REQUEST DETAIL</strong></div><div className="trace-row"><UserRound size={14} /><span>Requesting user</span><strong>{identityCopy.operatorDisplay}</strong></div><div className="trace-row"><Network size={14} /><span>DCS mapping</span><strong className="mono">NOT CONFIGURED · READ-ONLY</strong></div></div>{selected.status === "PENDING_OPERATOR" && <button className="primary-btn drawer-action" onClick={() => navigate("/approvals")}>REVIEW & APPROVE <Zap size={15} /></button>}</aside></div>}
    </div>
  );
}
function ArrowRightIcon() { return <ChevronRight size={18} className="compare-arrow" />; }
