/* Control Room Ledger: authentication is delegated to the server-backed Manus OAuth session. */
import { useState } from "react";
import { Activity, Check, LockKeyhole, ShieldCheck, Terminal, X } from "lucide-react";
import { startLogin } from "@/const";

export default function Login() {
  const [certificate, setCertificate] = useState(true);
  return <main className="login-shell"><div className="login-aside"><div className="login-brand"><span className="gate-mark"><span /><span /><i /></span><div><strong>JESA</strong><small>DIGITAL ENGINEERING</small></div></div><div className="login-aside-copy"><div className="eyebrow cobalt">SECURED OT / IT BOUNDARY</div><h1>Verification of Request</h1><p>Controlled access to the PAP Attack Reactor gateway. Every session is bound to a server-validated role, certificate posture, and auditable decision trail.</p><div className="login-line"><span className="live-dot" /> MODULE 3 / psM+O <Check size={13} /></div><div className="login-line"><span className="live-dot" /> MODULE 2 / DMZ <Check size={13} /></div><div className="login-line"><span className="live-dot" /> MODULE 1 / CPC <Check size={13} /></div></div><div className="login-foot">© 2026 JESA S.A. · CONFIDENTIAL — PROPRIETARY INFORMATION</div></div><section className="login-panel"><div className="login-panel-head"><div><div className="eyebrow cobalt">PAP ATTACK REACTOR CONTROL SYSTEM</div><h2>Sign in to VoR Gateway</h2><p>Authenticate before accessing operations or request governance.</p></div><div className="login-status"><span className="live-dot" /> SESSION GATE <small>READY</small></div></div><div className="certificate-check"><div className="cert-icon"><ShieldCheck size={17} /></div><div><strong>X.509 certificate posture</strong><small>{certificate ? "Certificate binding is ready for server verification." : "Certificate posture is not ready."}</small></div><button type="button" className={certificate ? "cert-valid" : "cert-invalid"} onClick={() => setCertificate(!certificate)} aria-label="Toggle certificate posture">{certificate ? <Check size={14} /> : <X size={14} />}</button></div><button className="secure-login" disabled={!certificate} onClick={() => startLogin()}>CONTINUE WITH SECURE AUTH <LockKeyhole size={15} /></button><div className="login-config"><Terminal size={13} /><span>Authentication is handled by the full-stack OAuth gateway. The server issues and validates the signed session; no production credential is embedded in this client.</span></div><div className="login-boundary"><span>SECURITY ZONE</span><strong>DMZ / AUTHENTICATION GATEWAY</strong><span>SERVER JWT SESSION</span></div></section></main>;
}
