import { and, desc, eq, gte, inArray, isNull, lte, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { approvals, auditEvents, authoritativeMasterGates, adapterActivationRuns, catalogImports, certificateTrustAnchors, certificateTrustAnchorRotations, certificateTrustAnchorRetirements, certificateTrustPolicies, equipment, InsertUser, notifications, reconciliationDiffs, reconciliationRuns, reconciliationSignoffs, requestHistory, users, validationChecks, variables, vorRequests } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { assertAppendOnlyAuditAction, type VorStatus } from "./vor";
import { canRetireTrustAnchor, evaluateCertificateExpiry, hasDualIndependentApproval, validateExpiryPolicy } from "./certificateTrust";
import { buildAnalyticsPayload, type AnalyticsFilters } from "./analytics";
import { notificationReadResult, persistNotificationRows, publishNotifications, type NotificationEvent } from "./notifications";
import type { CatalogImportParseResult, EquipmentImportRow, VariableImportRow } from "./catalogImport";
import { CONFIGURATION_GOVERNANCE_ACTIONS } from "./configurationAudit";
import { buildCertificateExpiryAlert } from "./certificateExpiryAlerts";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) throw new Error("Database is required for authenticated operations");
  const values: InsertUser = { openId: user.openId, name: user.name ?? null, email: user.email ?? null, loginMethod: user.loginMethod ?? null, lastSignedIn: user.lastSignedIn ?? new Date(), role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "operator"), active: user.active ?? 1 };
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name, email: values.email, loginMethod: values.loginMethod, lastSignedIn: values.lastSignedIn } });
}
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
function requestFilter(filters?: AnalyticsFilters) { const conditions = []; if (filters?.from) conditions.push(gte(vorRequests.createdAt, filters.from)); if (filters?.to) conditions.push(lte(vorRequests.createdAt, filters.to)); if (filters?.department && filters.department !== "ALL") conditions.push(eq(vorRequests.department, filters.department)); return conditions.length ? and(...conditions) : undefined; }
export async function listRequests(filters?: AnalyticsFilters) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const where = requestFilter(filters); return where ? db.select().from(vorRequests).where(where).orderBy(desc(vorRequests.createdAt)) : db.select().from(vorRequests).orderBy(desc(vorRequests.createdAt)); }
export async function getRequestByRequestId(requestId: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.select().from(vorRequests).where(eq(vorRequests.requestId, requestId)).limit(1); return result[0]; }
export async function listPendingApprovals() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const rows = await db.select({ id: approvals.id, requestId: vorRequests.requestId, requestDbId: approvals.requestId, requesterId: approvals.requesterId, decision: approvals.decision, createdAt: approvals.createdAt, currentPv: vorRequests.currentPv, requestedSp: vorRequests.requestedSp, status: vorRequests.status, priority: vorRequests.priority, equipmentTag: equipment.tag, equipmentName: equipment.name, variableTag: variables.tag, variableName: variables.name, unit: variables.unit, silClass: variables.silClass, certificateSubject: vorRequests.certificateSubject }).from(approvals).innerJoin(vorRequests, eq(approvals.requestId, vorRequests.id)).innerJoin(equipment, eq(vorRequests.equipmentId, equipment.id)).innerJoin(variables, eq(vorRequests.variableId, variables.id)).where(eq(approvals.decision, "PENDING")).orderBy(desc(approvals.createdAt)); return Promise.all(rows.map(async row => { const validationResults = await db.select({ checkType: validationChecks.checkType, result: validationChecks.result, ruleId: validationChecks.ruleId, actualValue: validationChecks.actualValue, expectedValue: validationChecks.expectedValue, explanation: validationChecks.explanation }).from(validationChecks).where(eq(validationChecks.requestId, row.requestDbId)).orderBy(validationChecks.sequence); const [creationAudit] = await db.select({ reason: auditEvents.reason }).from(auditEvents).where(and(eq(auditEvents.requestId, row.requestDbId), eq(auditEvents.action, "REQUEST_CREATED"))).orderBy(desc(auditEvents.createdAt)).limit(1); return { ...row, validationResults, reason: creationAudit?.reason ?? "No request-creation reason recorded." }; })); }
export async function listNotifications(recipientId: number, unreadOnly = false) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const where = unreadOnly ? and(eq(notifications.recipientId, recipientId), isNull(notifications.readAt)) : eq(notifications.recipientId, recipientId); return db.select().from(notifications).where(where).orderBy(desc(notifications.createdAt)).limit(100); }
export function getAffectedRowCount(result: unknown) { const candidate = Array.isArray(result) ? result[0] : result; if (!candidate || typeof candidate !== "object" || !("affectedRows" in candidate)) return null; return Number((candidate as { affectedRows: number }).affectedRows); }
export async function markNotificationRead(recipientId: number, notificationId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.id, notificationId), eq(notifications.recipientId, recipientId), isNull(notifications.readAt))); const affectedRows = getAffectedRowCount(result); return notificationReadResult(recipientId, recipientId, affectedRows ?? 0); }
export async function markAllNotificationsRead(recipientId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.recipientId, recipientId), isNull(notifications.readAt))); return { updated: getAffectedRowCount(result) ?? 0 }; }
export async function createAndPublishNotifications(event: Omit<NotificationEvent, "recipientId">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const recipients = await db.select({ id: users.id }).from(users).where(and(eq(users.active, 1), inArray(users.role, ["operator", "supervisor"]))); if (!recipients.length) return []; const rows = await persistNotificationRows(rowsToInsert => db.insert(notifications).values(rowsToInsert), recipients, event); publishNotifications(rows); return rows; }
export async function createCertificateExpiryNotifications() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const anchors = await listCertificateTrustAnchors(); const recipients = await db.select({ id: users.id }).from(users).where(and(eq(users.active, 1), inArray(users.role, ["operator", "supervisor"]))); const created: NotificationEvent[] = []; for (const anchor of anchors) { const event = buildCertificateExpiryAlert(anchor); if (!event) continue; const key = event.dedupeKey; const existing = key ? await db.select({ id: notifications.id }).from(notifications).where(and(eq(notifications.dedupeKey, key), inArray(notifications.recipientId, recipients.map(recipient => recipient.id)))).limit(1) : []; if (existing.length) continue; const rows = await persistNotificationRows(rowsToInsert => db.insert(notifications).values(rowsToInsert), recipients, event); created.push(...rows); } publishNotifications(created); return { created: created.length, alerts: created }; }
export async function listAuditEvents() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select().from(auditEvents).orderBy(desc(auditEvents.createdAt)).limit(200); }
export async function getEngineeringCatalog() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return { equipment: await db.select().from(equipment), variables: await db.select().from(variables) }; }
export async function listCatalogImports() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select().from(catalogImports).orderBy(desc(catalogImports.createdAt)).limit(50); }
export async function getCatalogImportById(id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [row] = await db.select().from(catalogImports).where(eq(catalogImports.id, id)).limit(1); return row; }
export async function listReconciliationRuns() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select().from(reconciliationRuns).orderBy(desc(reconciliationRuns.createdAt)).limit(50); }
export async function getReconciliationRunById(id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [row] = await db.select().from(reconciliationRuns).where(eq(reconciliationRuns.id, id)).limit(1); return row; }
export async function listReconciliationDiffs(runId: number, offset: number, limit: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const rows = await db.select().from(reconciliationDiffs).where(eq(reconciliationDiffs.reconciliationRunId, runId)).orderBy(reconciliationDiffs.sequence).limit(limit).offset(offset); const [{ count }] = await db.select({ count: sql<number>`count(*)` }).from(reconciliationDiffs).where(eq(reconciliationDiffs.reconciliationRunId, runId)); return { rows, total: Number(count || 0), offset, limit }; }
export async function listReconciliationSignoffs(runId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select().from(reconciliationSignoffs).where(eq(reconciliationSignoffs.reconciliationRunId, runId)).orderBy(desc(reconciliationSignoffs.signedAt)); }
export function normalizeMasterGate<T>(row: T | undefined): T | null { return row ?? null; }
export async function listConfigurationGovernanceAudit() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select({ id: auditEvents.id, actorId: auditEvents.actorId, actorRole: auditEvents.actorRole, action: auditEvents.action, result: auditEvents.result, reason: auditEvents.reason, module: auditEvents.module, certificateSubject: auditEvents.certificateSubject, createdAt: auditEvents.createdAt }).from(auditEvents).where(and(eq(auditEvents.module, "CONFIGURATION"), inArray(auditEvents.action, [...CONFIGURATION_GOVERNANCE_ACTIONS]))).orderBy(desc(auditEvents.createdAt)).limit(200); }
export async function getAuthoritativeMasterGate() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [row] = await db.select().from(authoritativeMasterGates).orderBy(desc(authoritativeMasterGates.activatedAt)).limit(1); return normalizeMasterGate(row); }
export async function getCertificateTrustPolicy() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [policy] = await db.select().from(certificateTrustPolicies).where(eq(certificateTrustPolicies.id, 1)).limit(1); return policy ?? { id: 1, warningDays: 30, criticalDays: 7, updatedBy: null, updatedAt: null }; }
export async function listCertificateTrustAnchors() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const policy = await getCertificateTrustPolicy(); const rows = await db.select().from(certificateTrustAnchors).orderBy(desc(certificateTrustAnchors.registeredAt)).limit(100); return rows.map(anchor => ({ ...anchor, expiry: evaluateCertificateExpiry(anchor.expiresAt, policy.warningDays, policy.criticalDays) })); }
export async function listTrustAnchorRotations() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select().from(certificateTrustAnchorRotations).orderBy(desc(certificateTrustAnchorRotations.createdAt)).limit(100); }
export async function listTrustAnchorRetirements() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select().from(certificateTrustAnchorRetirements).orderBy(desc(certificateTrustAnchorRetirements.createdAt)).limit(100); }
export async function retireCertificateTrustAnchor(args: { anchorId: number; replacementAnchorId: number; action: "REVOKED" | "RETIRED"; referenceId: string; referenceStorageKey: string; referenceStorageUrl: string; reason: string; actorId: number; actorRole: string; sourceIp?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); if (args.anchorId === args.replacementAnchorId) throw new Error("Replacement trust anchor must be different from the anchor being retired"); return db.transaction(async tx => { const [anchor] = await tx.select().from(certificateTrustAnchors).where(eq(certificateTrustAnchors.id, args.anchorId)).limit(1); const [replacement] = await tx.select().from(certificateTrustAnchors).where(eq(certificateTrustAnchors.id, args.replacementAnchorId)).limit(1); if (!anchor || anchor.status !== "ACTIVE") throw new Error("Only an active trust anchor can be retired"); if (!replacement || replacement.status !== "ACTIVE") throw new Error("Replacement trust anchor must be active"); if (replacement.expiresAt && replacement.expiresAt.getTime() <= Date.now()) throw new Error("Replacement trust anchor is expired"); const [rotation] = await tx.select().from(certificateTrustAnchorRotations).where(and(eq(certificateTrustAnchorRotations.oldAnchorId, anchor.id), eq(certificateTrustAnchorRotations.newAnchorId, replacement.id))).limit(1); if (!canRetireTrustAnchor({ anchorStatus: anchor?.status ?? "REVOKED", replacementStatus: replacement?.status ?? "REVOKED", hasVerifiedRotation: Boolean(rotation), replacementExpiresAt: replacement?.expiresAt })) throw new Error("Retirement requires active anchors, a non-expired replacement, and verified rotation evidence"); const [retirement] = await tx.insert(certificateTrustAnchorRetirements).values({ anchorId: anchor.id, replacementAnchorId: replacement.id, action: args.action, referenceId: args.referenceId, referenceStorageKey: args.referenceStorageKey, referenceStorageUrl: args.referenceStorageUrl, reason: args.reason, actorId: args.actorId }).$returningId(); await tx.update(certificateTrustAnchors).set({ status: args.action }).where(and(eq(certificateTrustAnchors.id, anchor.id), eq(certificateTrustAnchors.status, "ACTIVE"))); await tx.insert(auditEvents).values({ actorId: args.actorId, actorRole: args.actorRole, action: "TRUST_ANCHOR_RETIRED", result: args.action, reason: `Trust anchor ${anchor.fingerprint} ${args.action.toLowerCase()} after verified rotation to ${replacement.fingerprint}; evidence ${args.referenceId}.`, module: "CONFIGURATION", certificateSubject: anchor.subject, sourceIp: args.sourceIp }); return { retirementId: retirement.id, anchorId: anchor.id, replacementAnchorId: replacement.id, action: args.action, referenceId: args.referenceId, chainValidation: "OLD_ANCHOR_BLOCKED" as const }; }); }
export async function updateCertificateTrustPolicy(args: { warningDays: number; criticalDays: number; actorId: number; actorRole: string; sourceIp?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); if (!validateExpiryPolicy(args.warningDays, args.criticalDays)) throw new Error("Expiry policy requires integer thresholds from 0 to 3650 days, with warningDays greater than or equal to criticalDays"); await db.insert(certificateTrustPolicies).values({ id: 1, warningDays: args.warningDays, criticalDays: args.criticalDays, updatedBy: args.actorId }).onDuplicateKeyUpdate({ set: { warningDays: args.warningDays, criticalDays: args.criticalDays, updatedBy: args.actorId, updatedAt: new Date() } }); await db.insert(auditEvents).values({ actorId: args.actorId, actorRole: args.actorRole, action: "CERTIFICATE_EXPIRY_POLICY_UPDATED", result: "UPDATED", reason: `Certificate expiry warnings set to ${args.warningDays} days and critical threshold to ${args.criticalDays} days.`, module: "CONFIGURATION", certificateSubject: null, sourceIp: args.sourceIp }); return getCertificateTrustPolicy(); }
export async function persistCertificateTrustAnchor(args: { subject: string; fingerprint: string; validFrom?: Date | null; expiresAt?: Date | null; storageKey: string; storageUrl: string; registeredBy: number; actorRole: string; sourceIp?: string; rotation?: { oldAnchorId?: number; oldFingerprint?: string; referenceId: string; referenceStorageKey: string; referenceStorageUrl: string; reason: string } }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [anchor] = await db.insert(certificateTrustAnchors).values({ subject: args.subject, fingerprint: args.fingerprint, validFrom: args.validFrom ?? null, expiresAt: args.expiresAt ?? null, storageKey: args.storageKey, storageUrl: args.storageUrl, registeredBy: args.registeredBy, status: "ACTIVE" }).$returningId(); if (args.rotation) await db.insert(certificateTrustAnchorRotations).values({ oldAnchorId: args.rotation.oldAnchorId ?? null, oldFingerprint: args.rotation.oldFingerprint ?? null, newAnchorId: anchor.id, newFingerprint: args.fingerprint, referenceId: args.rotation.referenceId, referenceStorageKey: args.rotation.referenceStorageKey, referenceStorageUrl: args.rotation.referenceStorageUrl, reason: args.rotation.reason, actorId: args.registeredBy }); await db.insert(auditEvents).values({ actorId: args.registeredBy, actorRole: args.actorRole, action: "TRUST_ANCHOR_REGISTERED", result: "ACTIVE", reason: `Approved certificate trust anchor ${args.fingerprint} registered for chain validation${args.rotation ? ` with rotation evidence ${args.rotation.referenceId}` : ""}.`, module: "CONFIGURATION", certificateSubject: args.subject, sourceIp: args.sourceIp }); if (args.rotation) await db.insert(auditEvents).values({ actorId: args.registeredBy, actorRole: args.actorRole, action: "TRUST_ANCHOR_ROTATED", result: "EVIDENCE_RECORDED", reason: `Trust-anchor rotation evidence ${args.rotation.referenceId} links ${args.rotation.oldFingerprint || "previous anchor"} to ${args.fingerprint}.`, module: "CONFIGURATION", certificateSubject: args.subject, sourceIp: args.sourceIp }); return { trustAnchorId: anchor.id, subject: args.subject, fingerprint: args.fingerprint, status: "ACTIVE" as const, validFrom: args.validFrom ?? null, expiresAt: args.expiresAt ?? null, rotationEvidenceRecorded: Boolean(args.rotation) }; }
export async function listAdapterActivations() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select().from(adapterActivationRuns).orderBy(desc(adapterActivationRuns.createdAt)).limit(50); }
export async function prepareAdapterActivation(args: { gateId: number; actorId: number; actorRole: string; sourceIp?: string; fatSatReference: string; checklist: Record<string, boolean> }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const gate = await getAuthoritativeMasterGate(); if (!gate || gate.id !== args.gateId || gate.status !== "ARMED_FOR_FAT_SAT") throw new Error("Adapter activation requires an armed FAT/SAT gate"); if (Object.values(args.checklist).some(value => !value)) throw new Error("All post-FAT/SAT checklist controls must be confirmed"); const [activation] = await db.insert(adapterActivationRuns).values({ gateId: args.gateId, actorId: args.actorId, fatSatReference: args.fatSatReference, checklist: JSON.stringify(args.checklist), status: "READY_READ_ONLY", plantWriteEnabled: 0 }).$returningId(); await db.insert(auditEvents).values({ actorId: args.actorId, actorRole: args.actorRole, action: "ADAPTER_ACTIVATION_READY", result: "READY_READ_ONLY", reason: `Post-FAT/SAT adapter activation readiness recorded against gate ${args.gateId} and reference ${args.fatSatReference}. No connection was opened and plant writes remain disabled.`, module: "CONFIGURATION", certificateSubject: null, sourceIp: args.sourceIp }); return { activationId: activation.id, status: "READY_READ_ONLY" as const, plantWriteEnabled: false, connectionOpened: false, fatSatReference: args.fatSatReference }; }
export async function persistReconciliationRun(args: { actorId: number; actorRole: string; sourceIp?: string; recordType: "EQUIPMENT" | "VARIABLE"; authoritySourceRef: string; filename: string; storageKey: string; storageUrl: string; rowCount: number; diff: { status: "MATCHED" | "MISMATCH" | "BLOCKED"; fatSatGate: "BLOCKED" | "PENDING_EXTERNAL_SIGNOFF"; matchedCount: number; addedCount: number; changedCount: number; removedCount: number; differences: Array<{ tag: string; kind: string; details: string }> }; }) {
  const db = await getDb(); if (!db) throw new Error("Database unavailable");
  return db.transaction(async tx => {
    const [run] = await tx.insert(reconciliationRuns).values({ actorId: args.actorId, recordType: args.recordType, authoritySourceRef: args.authoritySourceRef, filename: args.filename, storageKey: args.storageKey, storageUrl: args.storageUrl, rowCount: args.rowCount, matchedCount: args.diff.matchedCount, addedCount: args.diff.addedCount, changedCount: args.diff.changedCount, removedCount: args.diff.removedCount, status: args.diff.status, fatSatGate: args.diff.fatSatGate, diffSummary: args.diff.differences.length ? args.diff.differences.slice(0, 100).map(diff => `${diff.kind} ${diff.tag}: ${diff.details}`).join("; ") : "No differences found against the canonical catalog." }).$returningId();
    if (args.diff.differences.length) await tx.insert(reconciliationDiffs).values(args.diff.differences.map((diff, index) => ({ reconciliationRunId: run.id, sequence: index + 1, tag: diff.tag, kind: diff.kind, details: diff.details })));
    await tx.insert(auditEvents).values({ actorId: args.actorId, actorRole: args.actorRole, action: "CATALOG_RECONCILIATION", result: args.diff.status, reason: `${args.recordType} reconciliation against authority ${args.authoritySourceRef}; run ${run.id}; FAT/SAT gate ${args.diff.fatSatGate}. No canonical catalog rows or plant systems were modified.`, module: "CONFIGURATION", certificateSubject: null, sourceIp: args.sourceIp });
    return { reconciliationRunId: run.id, ...args.diff, recordType: args.recordType, authoritySourceRef: args.authoritySourceRef, filename: args.filename, rowCount: args.rowCount };
  });
}
export async function persistReconciliationSignoff(args: { reconciliationRunId: number; actorId: number; actorRole: string; sourceIp?: string; certificateSubject: string; certificateFingerprint: string; certificateStorageKey: string; certificateStorageUrl: string; referenceId: string; referenceStorageKey: string; referenceStorageUrl: string; chainStatus: "VALID" | "INVALID" | "TRUST_STORE_MISSING"; decision: "APPROVED" | "REJECTED"; comment?: string; }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const run = await getReconciliationRunById(args.reconciliationRunId); if (!run) throw new Error("Reconciliation run not found"); if (run.status !== "MATCHED") throw new Error("Only an exact reconciliation match can receive external sign-off"); if (args.chainStatus !== "VALID") throw new Error("Certificate chain must validate against an active approved trust anchor"); const [signoff] = await db.insert(reconciliationSignoffs).values({ reconciliationRunId: args.reconciliationRunId, actorId: args.actorId, actorRole: args.actorRole, certificateSubject: args.certificateSubject, certificateFingerprint: args.certificateFingerprint, certificateStorageKey: args.certificateStorageKey, certificateStorageUrl: args.certificateStorageUrl, referenceId: args.referenceId, referenceStorageKey: args.referenceStorageKey, referenceStorageUrl: args.referenceStorageUrl, decision: args.decision, comment: args.comment, chainStatus: args.chainStatus }).$returningId(); await db.insert(auditEvents).values({ actorId: args.actorId, actorRole: args.actorRole, action: "RECONCILIATION_SIGNOFF", result: args.decision, reason: `Reconciliation run ${run.id} ${args.decision.toLowerCase()} with certificate ${args.certificateFingerprint} and reference ${args.referenceId}.`, module: "CONFIGURATION", certificateSubject: args.certificateSubject, sourceIp: args.sourceIp }); return { signoffId: signoff.id, reconciliationRunId: run.id, decision: args.decision, fatSatGate: args.decision === "APPROVED" ? "PENDING_MASTER_ARM" : "BLOCKED" }; }
export async function armAuthoritativeMaster(args: { reconciliationRunId: number; actorId: number; actorRole: string; sourceIp?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const run = await getReconciliationRunById(args.reconciliationRunId); if (!run || run.status !== "MATCHED") throw new Error("Authoritative master can only be armed from a MATCHED reconciliation run"); const signoffs = await listReconciliationSignoffs(run.id); if (!hasDualIndependentApproval(signoffs)) throw new Error("Two independent approved external sign-offs with valid certificate chains are required"); const [gate] = await db.insert(authoritativeMasterGates).values({ reconciliationRunId: run.id, activatedBy: args.actorId, authoritySourceRef: run.authoritySourceRef, status: "ARMED_FOR_FAT_SAT" }).$returningId(); await db.insert(auditEvents).values({ actorId: args.actorId, actorRole: args.actorRole, action: "AUTHORITATIVE_MASTER_ARMED", result: "ARMED_FOR_FAT_SAT", reason: `Authoritative master ${run.authoritySourceRef} armed after approved external evidence for reconciliation run ${run.id}. No plant connection or write path was activated.`, module: "CONFIGURATION", certificateSubject: null, sourceIp: args.sourceIp }); return { gateId: gate.id, status: "ARMED_FOR_FAT_SAT" as const, reconciliationRunId: run.id, authoritySourceRef: run.authoritySourceRef, plantWriteEnabled: false }; }
export async function persistCatalogImport(args: { actorId: number; actorRole: string; sourceIp?: string; filename: string; storageKey: string; storageUrl: string; parsed: CatalogImportParseResult; }) {
  const db = await getDb(); if (!db) throw new Error("Database unavailable");
  const { parsed } = args;
  return db.transaction(async tx => {
    let createdCount = 0; let updatedCount = 0;
    if (parsed.errors.length === 0 && parsed.rows.length > 0) {
      const tags = parsed.rows.map(row => row.tag);
      if (parsed.recordType === "EQUIPMENT") {
        const existing = await tx.select({ tag: equipment.tag }).from(equipment).where(inArray(equipment.tag, tags));
        await tx.insert(equipment).values(parsed.rows as EquipmentImportRow[]).onDuplicateKeyUpdate({ set: { name: sql`VALUES(name)`, processArea: sql`VALUES(processArea)`, sourceRef: sql`VALUES(sourceRef)` } });
        updatedCount = existing.length; createdCount = parsed.rows.length - updatedCount;
      } else {
        const existing = await tx.select({ tag: variables.tag }).from(variables).where(inArray(variables.tag, tags));
        await tx.insert(variables).values(parsed.rows as VariableImportRow[]).onDuplicateKeyUpdate({ set: { name: sql`VALUES(name)`, variableType: sql`VALUES(variableType)`, unit: sql`VALUES(unit)`, hardLow: sql`VALUES(hardLow)`, hardHigh: sql`VALUES(hardHigh)`, warningLow: sql`VALUES(warningLow)`, warningHigh: sql`VALUES(warningHigh)`, criticalLow: sql`VALUES(criticalLow)`, criticalHigh: sql`VALUES(criticalHigh)`, silClass: sql`VALUES(silClass)`, dcsMapping: sql`VALUES(dcsMapping)`, sourceRef: sql`VALUES(sourceRef)` } });
        updatedCount = existing.length; createdCount = parsed.rows.length - updatedCount;
      }
    }
    const status = parsed.errors.length ? "REJECTED" : "COMPLETED";
    const [importRun] = await tx.insert(catalogImports).values({ actorId: args.actorId, recordType: parsed.recordType, filename: args.filename, storageKey: args.storageKey, storageUrl: args.storageUrl, rowCount: parsed.rowCount, createdCount, updatedCount, rejectedCount: parsed.errors.length, status, errorSummary: parsed.errors.length ? parsed.errors.slice(0, 20).map(error => `row ${error.row}: ${error.message}`).join("; ") : null }).$returningId();
    await tx.insert(auditEvents).values({ actorId: args.actorId, actorRole: args.actorRole, action: "CATALOG_IMPORT", result: status, reason: `${parsed.recordType} catalog import ${args.filename}; import run ${importRun.id}; ${createdCount} created, ${updatedCount} updated, ${parsed.errors.length} rejected.`, module: "CONFIGURATION", certificateSubject: null, sourceIp: args.sourceIp });
    return { importRunId: importRun.id, recordType: parsed.recordType, status, rowCount: parsed.rowCount, createdCount, updatedCount, rejectedCount: parsed.errors.length, errors: parsed.errors.slice(0, 20) };
  });
}
export async function getAnalyticsSeries(filters?: AnalyticsFilters) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const transitionConditions = []; if (filters?.from) transitionConditions.push(gte(requestHistory.createdAt, filters.from)); if (filters?.to) transitionConditions.push(lte(requestHistory.createdAt, filters.to)); if (filters?.department && filters.department !== "ALL") transitionConditions.push(eq(vorRequests.department, filters.department)); const transitionWhere = transitionConditions.length ? and(...transitionConditions) : undefined; const transitionQuery = db.select({ fromStatus: requestHistory.fromStatus, toStatus: requestHistory.toStatus, createdAt: requestHistory.createdAt, department: vorRequests.department }).from(requestHistory).innerJoin(vorRequests, eq(requestHistory.requestId, vorRequests.id)); const transitionRows = await (transitionWhere ? transitionQuery.where(transitionWhere) : transitionQuery).orderBy(desc(requestHistory.createdAt)).limit(5000); const approvalConditions = []; if (filters?.from) approvalConditions.push(gte(approvals.createdAt, filters.from)); if (filters?.to) approvalConditions.push(lte(approvals.createdAt, filters.to)); if (filters?.department && filters.department !== "ALL") approvalConditions.push(eq(vorRequests.department, filters.department)); const approvalWhere = approvalConditions.length ? and(...approvalConditions) : undefined; const approvalQuery = db.select({ createdAt: approvals.createdAt, decidedAt: approvals.decidedAt, decision: approvals.decision, department: vorRequests.department }).from(approvals).innerJoin(vorRequests, eq(approvals.requestId, vorRequests.id)); const approvalRows = await (approvalWhere ? approvalQuery.where(approvalWhere) : approvalQuery).orderBy(desc(approvals.createdAt)).limit(5000); const requestRows = await db.select({ createdAt: vorRequests.createdAt, department: vorRequests.department, status: vorRequests.status, sourceUc: vorRequests.sourceUc, priority: vorRequests.priority, silClass: variables.silClass, equipmentTag: equipment.tag, variableTag: variables.tag }).from(vorRequests).innerJoin(equipment, eq(vorRequests.equipmentId, equipment.id)).innerJoin(variables, eq(vorRequests.variableId, variables.id)).orderBy(desc(vorRequests.createdAt)).limit(5000); const validationRows = await db.select({ createdAt: validationChecks.executedAt, requestCreatedAt: vorRequests.createdAt, department: vorRequests.department, checkType: validationChecks.checkType, result: validationChecks.result }).from(validationChecks).innerJoin(vorRequests, eq(validationChecks.requestId, vorRequests.id)).orderBy(desc(validationChecks.executedAt)).limit(10000); return buildAnalyticsPayload(transitionRows, approvalRows, filters, requestRows, validationRows); }
export async function recordAudit(event: typeof auditEvents.$inferInsert) { assertAppendOnlyAuditAction(event.action); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(auditEvents).values(event); }
export async function transitionRequest(requestId: number, actorId: number, actorRole: string, fromStatus: VorStatus, toStatus: VorStatus, reason: string, sourceIp?: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); let events: NotificationEvent[] = []; const result = await db.transaction(async tx => { const updated = await tx.update(vorRequests).set({ status: toStatus }).where(and(eq(vorRequests.id, requestId), eq(vorRequests.status, fromStatus))); if (!updated[0] || ("affectedRows" in updated[0] && updated[0].affectedRows !== 1)) throw new Error("Concurrent request state change detected"); await tx.insert(requestHistory).values({ requestId, actorId, fromStatus, toStatus, reason }); await tx.insert(auditEvents).values({ requestId, actorId, actorRole, action: "REQUEST_STATE_TRANSITION", previousState: fromStatus, newState: toStatus, result: "COMMITTED", reason, module: "DMZ", sourceIp }); const recipients = await tx.select({ id: users.id }).from(users).where(and(eq(users.active, 1), inArray(users.role, ["operator", "supervisor"]))); events = recipients.map(recipient => ({ recipientId: recipient.id, requestId, type: "STATE_CHANGED" as const, severity: toStatus === "REJECTED" ? "WARNING" as const : "INFO" as const, title: `Request ${toStatus.toLowerCase().replaceAll("_", " ")}`, message: `Request state changed from ${fromStatus} to ${toStatus}.`, })); if (events.length) await tx.insert(notifications).values(events); return tx.select().from(vorRequests).where(eq(vorRequests.id, requestId)).limit(1); }); publishNotifications(events); return result; }
