import { and, desc, eq, gte, inArray, isNull, lte } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { approvals, auditEvents, equipment, InsertUser, notifications, requestHistory, users, validationChecks, variables, vorRequests } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { assertAppendOnlyAuditAction, type VorStatus } from "./vor";
import { buildAnalyticsPayload, type AnalyticsFilters } from "./analytics";
import { notificationReadResult, persistNotificationRows, publishNotifications, type NotificationEvent } from "./notifications";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) throw new Error("Database is required for authenticated operations");
  const values: InsertUser = { openId: user.openId, name: user.name ?? null, email: user.email ?? null, loginMethod: user.loginMethod ?? null, lastSignedIn: user.lastSignedIn ?? new Date(), role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "operator"), active: user.active ?? 1 };
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name, email: values.email, loginMethod: values.loginMethod, lastSignedIn: values.lastSignedIn } });
}
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
function requestFilter(filters?: AnalyticsFilters) { const conditions = []; if (filters?.from) conditions.push(gte(vorRequests.createdAt, filters.from)); if (filters?.to) conditions.push(lte(vorRequests.createdAt, filters.to)); if (filters?.department && filters.department !== "ALL") conditions.push(eq(vorRequests.department, filters.department)); return conditions.length ? and(...conditions) : undefined; }
export async function listRequests(filters?: AnalyticsFilters) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const where = requestFilter(filters); return where ? db.select().from(vorRequests).where(where).orderBy(desc(vorRequests.createdAt)) : db.select().from(vorRequests).orderBy(desc(vorRequests.createdAt)); }
export async function getRequestByRequestId(requestId: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.select().from(vorRequests).where(eq(vorRequests.requestId, requestId)).limit(1); return result[0]; }
export async function listPendingApprovals() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const rows = await db.select({ id: approvals.id, requestId: vorRequests.requestId, requestDbId: approvals.requestId, requesterId: approvals.requesterId, decision: approvals.decision, createdAt: approvals.createdAt, currentPv: vorRequests.currentPv, requestedSp: vorRequests.requestedSp, status: vorRequests.status, priority: vorRequests.priority, equipmentTag: equipment.tag, equipmentName: equipment.name, variableTag: variables.tag, variableName: variables.name, unit: variables.unit, silClass: variables.silClass, certificateSubject: vorRequests.certificateSubject }).from(approvals).innerJoin(vorRequests, eq(approvals.requestId, vorRequests.id)).innerJoin(equipment, eq(vorRequests.equipmentId, equipment.id)).innerJoin(variables, eq(vorRequests.variableId, variables.id)).where(eq(approvals.decision, "PENDING")).orderBy(desc(approvals.createdAt)); return Promise.all(rows.map(async row => { const validationResults = await db.select({ checkType: validationChecks.checkType, result: validationChecks.result, ruleId: validationChecks.ruleId, actualValue: validationChecks.actualValue, expectedValue: validationChecks.expectedValue, explanation: validationChecks.explanation }).from(validationChecks).where(eq(validationChecks.requestId, row.requestDbId)).orderBy(validationChecks.sequence); const [creationAudit] = await db.select({ reason: auditEvents.reason }).from(auditEvents).where(and(eq(auditEvents.requestId, row.requestDbId), eq(auditEvents.action, "REQUEST_CREATED"))).orderBy(desc(auditEvents.createdAt)).limit(1); return { ...row, validationResults, reason: creationAudit?.reason ?? "No request-creation reason recorded." }; })); }
export async function listNotifications(recipientId: number, unreadOnly = false) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const where = unreadOnly ? and(eq(notifications.recipientId, recipientId), isNull(notifications.readAt)) : eq(notifications.recipientId, recipientId); return db.select().from(notifications).where(where).orderBy(desc(notifications.createdAt)).limit(100); }
export async function markNotificationRead(recipientId: number, notificationId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.id, notificationId), eq(notifications.recipientId, recipientId), isNull(notifications.readAt))); return "affectedRows" in result ? notificationReadResult(recipientId, recipientId, Number(result.affectedRows)) : { updated: true }; }
export async function createAndPublishNotifications(event: Omit<NotificationEvent, "recipientId">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const recipients = await db.select({ id: users.id }).from(users).where(and(eq(users.active, 1), inArray(users.role, ["operator", "supervisor"]))); if (!recipients.length) return []; const rows = await persistNotificationRows(rowsToInsert => db.insert(notifications).values(rowsToInsert), recipients, event); publishNotifications(rows); return rows; }
export async function listAuditEvents() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.select().from(auditEvents).orderBy(desc(auditEvents.createdAt)).limit(200); }
export async function getEngineeringCatalog() { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return { equipment: await db.select().from(equipment), variables: await db.select().from(variables) }; }
export async function getAnalyticsSeries(filters?: AnalyticsFilters) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const transitionConditions = []; if (filters?.from) transitionConditions.push(gte(requestHistory.createdAt, filters.from)); if (filters?.to) transitionConditions.push(lte(requestHistory.createdAt, filters.to)); if (filters?.department && filters.department !== "ALL") transitionConditions.push(eq(vorRequests.department, filters.department)); const transitionWhere = transitionConditions.length ? and(...transitionConditions) : undefined; const transitionQuery = db.select({ fromStatus: requestHistory.fromStatus, toStatus: requestHistory.toStatus, createdAt: requestHistory.createdAt, department: vorRequests.department }).from(requestHistory).innerJoin(vorRequests, eq(requestHistory.requestId, vorRequests.id)); const transitionRows = await (transitionWhere ? transitionQuery.where(transitionWhere) : transitionQuery).orderBy(desc(requestHistory.createdAt)).limit(5000); const approvalConditions = []; if (filters?.from) approvalConditions.push(gte(approvals.createdAt, filters.from)); if (filters?.to) approvalConditions.push(lte(approvals.createdAt, filters.to)); if (filters?.department && filters.department !== "ALL") approvalConditions.push(eq(vorRequests.department, filters.department)); const approvalWhere = approvalConditions.length ? and(...approvalConditions) : undefined; const approvalQuery = db.select({ createdAt: approvals.createdAt, decidedAt: approvals.decidedAt, decision: approvals.decision, department: vorRequests.department }).from(approvals).innerJoin(vorRequests, eq(approvals.requestId, vorRequests.id)); const approvalRows = await (approvalWhere ? approvalQuery.where(approvalWhere) : approvalQuery).orderBy(desc(approvals.createdAt)).limit(5000); const requestRows = await db.select({ createdAt: vorRequests.createdAt, department: vorRequests.department, status: vorRequests.status, sourceUc: vorRequests.sourceUc, priority: vorRequests.priority, silClass: variables.silClass, equipmentTag: equipment.tag, variableTag: variables.tag }).from(vorRequests).innerJoin(equipment, eq(vorRequests.equipmentId, equipment.id)).innerJoin(variables, eq(vorRequests.variableId, variables.id)).orderBy(desc(vorRequests.createdAt)).limit(5000); const validationRows = await db.select({ createdAt: validationChecks.executedAt, requestCreatedAt: vorRequests.createdAt, department: vorRequests.department, checkType: validationChecks.checkType, result: validationChecks.result }).from(validationChecks).innerJoin(vorRequests, eq(validationChecks.requestId, vorRequests.id)).orderBy(desc(validationChecks.executedAt)).limit(10000); return buildAnalyticsPayload(transitionRows, approvalRows, filters, requestRows, validationRows); }
export async function recordAudit(event: typeof auditEvents.$inferInsert) { assertAppendOnlyAuditAction(event.action); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(auditEvents).values(event); }
export async function transitionRequest(requestId: number, actorId: number, actorRole: string, fromStatus: VorStatus, toStatus: VorStatus, reason: string, sourceIp?: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); let events: NotificationEvent[] = []; const result = await db.transaction(async tx => { const updated = await tx.update(vorRequests).set({ status: toStatus }).where(and(eq(vorRequests.id, requestId), eq(vorRequests.status, fromStatus))); if (!updated[0] || ("affectedRows" in updated[0] && updated[0].affectedRows !== 1)) throw new Error("Concurrent request state change detected"); await tx.insert(requestHistory).values({ requestId, actorId, fromStatus, toStatus, reason }); await tx.insert(auditEvents).values({ requestId, actorId, actorRole, action: "REQUEST_STATE_TRANSITION", previousState: fromStatus, newState: toStatus, result: "COMMITTED", reason, module: "DMZ", sourceIp }); const recipients = await tx.select({ id: users.id }).from(users).where(and(eq(users.active, 1), inArray(users.role, ["operator", "supervisor"]))); events = recipients.map(recipient => ({ recipientId: recipient.id, requestId, type: "STATE_CHANGED" as const, severity: toStatus === "REJECTED" ? "WARNING" as const : "INFO" as const, title: `Request ${toStatus.toLowerCase().replaceAll("_", " ")}`, message: `Request state changed from ${fromStatus} to ${toStatus}.`, })); if (events.length) await tx.insert(notifications).values(events); return tx.select().from(vorRequests).where(eq(vorRequests.id, requestId)).limit(1); }); publishNotifications(events); return result; }
