import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { approvals, auditEvents, requestHistory, validationChecks, vorRequests } from "../drizzle/schema";
import { and, desc, eq } from "drizzle-orm";
import { createAndPublishNotifications, getAnalyticsSeries, getDb, getRequestByRequestId, listAuditEvents, listNotifications, listPendingApprovals, listRequests, markNotificationRead, recordAudit, transitionRequest } from "./db";
import { assertFourEyes, assertRole, assertTransition, createDcsAcknowledgment, type Role, type VorStatus } from "./vor";
import { getEdgeAdapterHealth } from "./edgeAdapter";

const roleProcedure = (allowed: readonly Role[]) => protectedProcedure.use(async ({ ctx, next }) => { assertRole(ctx.user.role, allowed); return next({ ctx }); });
const operatorProcedure = roleProcedure(["operator", "supervisor", "engineer", "admin"]);
const supervisorProcedure = roleProcedure(["supervisor", "engineer", "admin"]);
const engineerProcedure = roleProcedure(["engineer", "admin"]);
const adminProcedure = roleProcedure(["admin"]);
const analyticsFilterInput = z.object({ from: z.coerce.date().optional(), to: z.coerce.date().optional(), department: z.enum(["ALL", "OPERATIONS", "MAINTENANCE", "PROCESS_CONTROL", "INSTRUMENTATION", "ELECTRICAL", "IT_OT_SECURITY"]).optional() }).optional();

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  requests: router({
    list: protectedProcedure.input(z.object({ status: z.string().optional(), query: z.string().optional() }).optional()).query(async ({ input }) => { const rows = await listRequests(); const q = input?.query?.toLowerCase(); return rows.filter(row => (!input?.status || row.status === input.status) && (!q || `${row.requestId} ${row.sourceUc} ${row.sourceIdentity}`.toLowerCase().includes(q))); }),
    detail: protectedProcedure.input(z.object({ requestId: z.string() })).query(async ({ input }) => { const db = await getDb(); const request = await getRequestByRequestId(input.requestId); if (!db || !request) throw new TRPCError({ code: "NOT_FOUND", message: "Request not found" }); const checks = await db.select().from(validationChecks).where(eq(validationChecks.requestId, request.id)); const history = await db.select().from(requestHistory).where(eq(requestHistory.requestId, request.id)).orderBy(desc(requestHistory.createdAt)); return { request, checks, history }; }),
    transition: supervisorProcedure.input(z.object({ requestId: z.string(), toStatus: z.enum(["ACCEPTED", "REJECTED", "PENDING_OPERATOR", "DUPLICATED", "EXPIRED"]), reason: z.string().min(3) })).mutation(async ({ input, ctx }) => { const request = await getRequestByRequestId(input.requestId); if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "Request not found" }); assertTransition(request.status as VorStatus, input.toStatus); const updated = await transitionRequest(request.id, ctx.user.id, ctx.user.role, request.status as VorStatus, input.toStatus, input.reason, ctx.req.ip); await createAndPublishNotifications({ requestId: request.id, type: "STATE_CHANGED", severity: input.toStatus === "REJECTED" ? "WARNING" : "INFO", title: `Request ${input.toStatus.toLowerCase().replaceAll("_", " ")}`, message: `${request.requestId} changed from ${request.status} to ${input.toStatus}.` }); return updated[0]; }),
  }),
  approvals: router({
    raise: operatorProcedure.input(z.object({ requestId: z.string() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const request = await getRequestByRequestId(input.requestId); if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "Request not found" }); if (request.requesterId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN", message: "Only the authenticated requester may raise approval" }); if (request.status !== "PENDING_OPERATOR") throw new TRPCError({ code: "CONFLICT", message: "Approval can only be raised for a pending request" }); const existing = await db.select().from(approvals).where(and(eq(approvals.requestId, request.id), eq(approvals.decision, "PENDING"))).limit(1); if (existing.length) throw new TRPCError({ code: "CONFLICT", message: "An approval is already pending" }); await db.insert(approvals).values({ requestId: request.id, requesterId: ctx.user.id }); await createAndPublishNotifications({ requestId: request.id, type: "APPROVAL_REQUIRED", severity: "WARNING", title: "Approval required", message: `${request.requestId} requires independent operator or supervisor review.` }); return { success: true, requestId: request.requestId }; }),
    pending: supervisorProcedure.query(() => listPendingApprovals()),
    decide: supervisorProcedure.input(z.object({ approvalId: z.number().int().positive(), decision: z.enum(["APPROVED", "REJECTED"]), comment: z.string().min(3) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const approval = (await db.select().from(approvals).where(eq(approvals.id, input.approvalId)).limit(1))[0]; if (!approval) throw new TRPCError({ code: "NOT_FOUND", message: "Approval not found" }); assertFourEyes(approval.requesterId, ctx.user.id); if (approval.decision !== "PENDING") throw new TRPCError({ code: "CONFLICT", message: "Approval is already decided" }); const request = (await db.select().from(vorRequests).where(eq(vorRequests.id, approval.requestId)).limit(1))[0]; if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "Request not found" }); const nextStatus = input.decision === "APPROVED" ? "ACCEPTED" : "REJECTED"; assertTransition(request.status as VorStatus, nextStatus); await db.transaction(async tx => { const approvalUpdate = await tx.update(approvals).set({ approverId: ctx.user.id, decision: input.decision, comment: input.comment, decidedAt: new Date() }).where(and(eq(approvals.id, input.approvalId), eq(approvals.decision, "PENDING"))) as unknown as { affectedRows: number }; if (approvalUpdate.affectedRows !== 1) throw new TRPCError({ code: "CONFLICT", message: "Approval was decided concurrently" }); const requestUpdate = await tx.update(vorRequests).set({ status: nextStatus }).where(and(eq(vorRequests.id, request.id), eq(vorRequests.status, request.status))) as unknown as { affectedRows: number }; if (requestUpdate.affectedRows !== 1) throw new TRPCError({ code: "CONFLICT", message: "Request state changed concurrently" }); await tx.insert(requestHistory).values({ requestId: request.id, actorId: ctx.user.id, fromStatus: request.status as VorStatus, toStatus: nextStatus, reason: input.comment }); await tx.insert(auditEvents).values({ requestId: request.id, actorId: ctx.user.id, actorRole: ctx.user.role, action: `APPROVAL_${input.decision}`, previousState: request.status, newState: nextStatus, result: "COMMITTED", reason: input.comment, module: "CPC", sourceIp: ctx.req.ip }); }); await createAndPublishNotifications({ requestId: request.id, type: "STATE_CHANGED", severity: nextStatus === "REJECTED" ? "WARNING" : "INFO", title: `Request ${nextStatus.toLowerCase()}`, message: `${request.requestId} changed to ${nextStatus} after approval decision.` }); return { success: true, requestId: request.requestId, status: nextStatus }; }),
  }),
  validation: router({ list: engineerProcedure.input(z.object({ requestId: z.string().optional() }).optional()).query(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); if (input?.requestId) { const request = await getRequestByRequestId(input.requestId); if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "Request not found" }); return db.select().from(validationChecks).where(eq(validationChecks.requestId, request.id)); } return db.select().from(validationChecks).orderBy(desc(validationChecks.executedAt)).limit(200); }),
  }),
  audit: router({ list: engineerProcedure.query(() => listAuditEvents()) }),
  systemHealth: router({ summary: protectedProcedure.query(() => ({ zones: [{ module: "psM+O", status: "ONLINE" }, { module: "DMZ", status: "ONLINE" }, { module: "CPC", status: "ONLINE" }], dcs: getEdgeAdapterHealth(), generatedAt: new Date() })) }),
  analytics: router({ summary: engineerProcedure.input(analyticsFilterInput).query(async ({ input }) => { const rows = await listRequests(input); const series = await getAnalyticsSeries(input); const total = rows.length; return { total, accepted: rows.filter(row => row.status === "ACCEPTED").length, rejected: rows.filter(row => row.status === "REJECTED").length, pending: rows.filter(row => row.status === "PENDING_OPERATOR").length, duplicated: rows.filter(row => row.status === "DUPLICATED").length, expired: rows.filter(row => row.status === "EXPIRED").length, ...series }; }) }),
  notifications: router({ list: protectedProcedure.input(z.object({ unreadOnly: z.boolean().optional() }).optional()).query(({ ctx, input }) => listNotifications(ctx.user.id, input?.unreadOnly ?? false)), markRead: protectedProcedure.input(z.object({ notificationId: z.number().int().positive() })).mutation(({ ctx, input }) => markNotificationRead(ctx.user.id, input.notificationId)) }),
  dcs: router({ acknowledge: supervisorProcedure.input(z.object({ requestId: z.string() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const request = await getRequestByRequestId(input.requestId); if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "Request not found" }); const checks = await db.select().from(validationChecks).where(eq(validationChecks.requestId, request.id)); const acknowledgment = createDcsAcknowledgment(request.requestId, request.status as VorStatus, checks.map(check => ({ checkType: check.checkType, result: check.result, ruleId: check.ruleId, actualValue: check.actualValue || "", expectedValue: check.expectedValue || "", explanation: check.explanation || "" }))); await recordAudit({ requestId: request.id, actorId: ctx.user.id, actorRole: ctx.user.role, action: "DCS_ACKNOWLEDGED", previousState: request.status, newState: request.status, result: "ACKNOWLEDGED", reason: "DCS adapter acknowledgment committed", module: "DCS", sourceIp: ctx.req.ip }); return acknowledgment; }) }),
  configuration: router({ policy: adminProcedure.query(() => ({ statuses: ["ACCEPTED", "REJECTED", "PENDING_OPERATOR", "DUPLICATED", "EXPIRED"], checks: ["EQUIPMENT_CHECK", "SIGNATURE_CHECK", "UNIT_CHECK", "DUPLICATE_CHECK", "TTL_CHECK", "RANGE_CHECK", "SIL_CHECK", "ROC_CHECK", "INTERLOCK_CHECK"], roles: ["operator", "supervisor", "engineer", "admin"], edgeAdapter: getEdgeAdapterHealth() })) }),
});

export type AppRouter = typeof appRouter;
